# Default values for cray-externaldns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

external-dns:
  image:
    registry: docker.io
    repository: bitnami/external-dns
    tag: 0.5.16-debian-9-r8
  podAnnotations:
    # Disable istio sidecar since etcd doesn't use it.
    sidecar.istio.io/inject: "false"
  rbac:
    # If true, create & use RBAC resources
    create: true
    pspEnabled: true
  sources:
    - "service"
    - "istio-gateway"
    - "ingress"
  policy: sync
  istioIngressGateways:
    - "istio-system/istio-ingressgateway"
  provider: "coredns"
  provider: "pdns"
  pdns:
    apiUrl: http://cray-dns-powerdns-api
    apiPort: 8081
    secretName: cray-powerdns-credentials
  crd:
    create: true
  metrics:
    enabled: true
  resources:
    limits:
      cpu: "2"
      memory: 256Mi
    requests:
      memory: 50Mi
      cpu: 10m
  livenessProbe:
    initialDelaySeconds: 31
    periodSeconds: 30
    failureThreshold: 1
    successThreshold: 1
    timeoutSeconds: 20
  readinessProbe:
    initialDelaySeconds: 1
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 7

sealedSecrets: []
